#!/bin/bash

# May 2021 - Gene Weber 
# This script launches ingest clients on the nodes running tservers.
# It's recommended to run 1-3 clients per teserver on the node.
#
# COMMAND LINE OPTIONS: If this script is launched with the command line option "split"
# it will pre-split the ci table using the "splits" file which must exist!!
#
# All settings for this test are in acc_test.conf.

# Save command line option
COMMAND_OPTION=$1

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars

echo ""
echo "All options are set in acc_test.conf"
echo "Current options: $CI_OPTS"
echo "Number of ingest clients per tserver: $INGEST_CLI_TSERVER"
echo "Number of ingest clients per node: $INGEST_CLI_NODE"
echo ""

# Create a new Continuous Ingest table in the accumulo database
echo ""
echo "Re-initializing the Ingest table"
echo ""
# Check if ci table already exists
echo -e "tables\nbye\n" | accumulo shell -u root | grep "^ci$" 2>/dev/null >/dev/null
# Delete it if it does
if [ "$?" == "0" ]; then
  echo -e "deletetable ci\nyes\nbye\n" | accumulo shell -u root 2>/dev/null >/dev/null
fi
# Create a new empty table. Pre-split the table if the split option was specified.
cingest createtable
if [ "$COMMAND_OPTION" == "split" ]; then
  echo -e "merge -t ci -f -v\nyes\nsleep 5\naddsplits -sf splits -t ci\nbye\n" \
       | accumulo shell -u root
fi

# Loop through each tserver node and remove any old logs
for node in $ACC_TSERVER_NODES
do
  pdsh -w $node "rm $LOCAL_NVME1/$ACC_LOG_DIR/ingest_* 2>/dev/null" 2>/dev/null &
done

# Give Accumulo time to apply tablet splits and stabilize.
if [ "$COMMAND_OPTION" == "split" ]; then
  WAIT_TIME=$NEW_TAB_WAIT_SPLIT
else
  WAIT_TIME=$NEW_TAB_WAIT_NOSPLIT
fi
echo ""
date
echo "Giving Accumulo $WAIT_TIME to become stable"
echo ""
sleep $WAIT_TIME

# Loop through each tserver node and launch ingest clients on each
for node in $ACC_TSERVER_NODES
do
  for (( i=1; i<=$INGEST_CLI_NODE; i++ ))
  do
    echo "Starting ingest client-${i} on $node"
    LOGFILE="/$LOCAL_NVME1/$ACC_LOG_DIR/ingest_${node}_${i}.log"
    ERRFILE="/$LOCAL_NVME1/$ACC_LOG_DIR/ingest_${node}_${i}.err"
    # CI_OPTS (continuous ingest options) are set in acc_test.conf
    # The following optimizes differently on different systems.
    if [ "$AWS" = true ]; then
      pdsh -w $node "nohup cingest ingest $CI_OPTS >$LOGFILE 2>$ERRFILE < /dev/null &" &
    else
      pdsh -w $node "nohup cingest ingest $CI_OPTS >$LOGFILE 2>$ERRFILE < /dev/null &"
    fi
  done
done
echo $(date +%s) > ingest_start #Capture start time.

# Loop through each tserver node and write the associated pids to the PID file.
PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/ingest_clients.pid"
echo ""
echo "Collecting and saving pid information."
sleep 5 # Make sure clients hace a chance to start.
for node in $ACC_TSERVER_NODES
do
  pdsh -w $node "ps -fu $LOGNAME | grep '\ ingest\ ' | sed 's/^$LOGNAME *//' | sed 's/\ .*$//' >$PIDFILE" &
done

