#!/bin/bash

# June 2021 - Gene Weber 
# This script simply launches the verify table test script on the specified node.
# See the verify table test script for more information.

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars
# Set bashrc flag
touch script_active

# Only move files and run via pdsh if running on a different node than logged into
if [[ "$VER_NODE" != "$LOCAL_NODE" ]]; then
  cp inst_dir verify_table acc_test.conf $INSTALL_DIR
  pdsh -w $VER_NODE 'cp $INSTALL_DIR/inst_dir .'
  pdsh -w $VER_NODE 'cp $INSTALL_DIR/verify_table .'
  pdsh -w $VER_NODE 'cp $INSTALL_DIR/acc_test.conf .'
  pdsh -w $VER_NODE './verify_table'
  rm $INSTALL_DIR/inst_dir $INSTALL_DIR/verify_table $INSTALL_DIR/acc_test.conf
  pdsh -w $VER_NODE 'rm inst_dir verify_table acc_test.conf'
else
  ./verify_table
fi

rm script_active
