#!/bin/bash

# June 2021 - Gene Weber 
# This script launches ingest clients on the nodes running tservers.
# It's recommended to run 1-3 clients per teserver on the node.
#
# COMMAND LINE OPTIONS: If this script is launched with the command line option "split"
# it will pre-split the ci table using the "splits" file which must exist!!
#
# All settings for this test are in acc_test.conf.

# Save command line option
COMMAND_OPTION=$1

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars

echo ""
echo "All options are set in acc_test.conf"
echo "Current options: $CI_OPTS"
echo "Number of ingest clients per tserver: $INGEST_CLI_TSERVER"
echo "Number of ingest clients per node: $INGEST_CLI_NODE"
echo ""

# Create a new Continuous Ingest table in the accumulo database
echo ""
echo "Re-initializing the Ingest table"
echo ""
# Check if ci table already exists
echo -e "tables\nbye\n" | accumulo shell -u root | grep "^ci$" 2>/dev/null >/dev/null
# Delete it if it does
if [ "$?" == "0" ]; then
  echo -e "deletetable ci\nyes\nbye\n" | accumulo shell -u root 2>/dev/null >/dev/null
fi
# Create a new empty table. Pre-split the table if the split option was specified.
cingest createtable
if [ "$COMMAND_OPTION" == "split" ]; then
  echo -e "merge -t ci -f -v\nyes\nsleep 5\naddsplits -sf splits -t ci\nbye\n" \
       | accumulo shell -u root
fi

# Remove all old ingest logs.
pdsh -w ^$INSTALL_DIR/acctservernodes "rm /$LOCAL_NVME1/$ACC_LOG_DIR/ingest_* 2>/dev/null" 2>/dev/null &

# Give Accumulo time to apply tablet splits and stabilize.
if [ "$COMMAND_OPTION" == "split" ]; then
  WAIT_TIME=$NEW_TAB_WAIT_SPLIT
else
  WAIT_TIME=$NEW_TAB_WAIT_NOSPLIT
fi
echo ""
date
echo "Giving Accumulo $WAIT_TIME to become stable"
echo ""
sleep $WAIT_TIME

# Create ingest clients launch file
rm $INSTALL_DIR/lnch_iclients 2>/dev/null
touch $INSTALL_DIR/lnch_iclients
chmod 755 $INSTALL_DIR/lnch_iclients
for (( i=1; i<=$INGEST_CLI_NODE; i++ ))
do
  LOGFILE="/$LOCAL_NVME1/$ACC_LOG_DIR/ingest_${i}.log"
  ERRFILE="/$LOCAL_NVME1/$ACC_LOG_DIR/ingest_${i}.err"
  echo "nohup cingest ingest $CI_OPTS >$LOGFILE 2>$ERRFILE < /dev/null &" >> $INSTALL_DIR/lnch_iclients
done
# Copy the launch file to local drive. This is more for AWS where nfs is slow!
pdsh -w ^$INSTALL_DIR/acctservernodes 'cp $INSTALL_DIR/lnch_iclients /$LOCAL_NVME1'

# Start the accumulo tablet servers.
echo "Launching $INGEST_CLI_NODE Ingest Clients on each of these nodes:"
echo $ACC_TSERVER_NODES
pdsh -w ^$INSTALL_DIR/acctservernodes 'nohup /$LOCAL_NVME1/lnch_iclients &' &
# Capture start time.
ING_START=$(date +%s)
echo $ING_START > ingest_start

# Allow some time for all client processes to start.
echo "Waiting $ICS_WAIT_TIME seconds for all Ingest Clients to start."
sleep ${ICS_WAIT_TIME}s

# Collect all ingest client PIDs
echo "Collecting all Ingest Client PIDs."
PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/ingest_clients.pid"
pdsh -w ^$INSTALL_DIR/acctservernodes "ps -fu $LOGNAME | grep '\ ingest\ ' | sed 's/^$LOGNAME *//' | sed 's/\ .*$//' >$PIDFILE"

# Verify the Ingest Clients
cat <<EOT > $INSTALL_DIR/iclient_verify
LONGEST=0
NUM_PIDS=0
for pid in \$(cat $PIDFILE)
do
  ((NUM_PIDS++))
  TEMP1=\$(export TZ=UTC0 LC_ALL=C; date -d "\$(ps -o lstart= \$pid)" +%s)
  TEMP=\$((\$TEMP1 - $ING_START))
  if (( \$TEMP > \$LONGEST )); then
    LONGEST=\$TEMP
  fi
done

if (($INGEST_CLI_NODE > \$NUM_PIDS)); then
  echo "ERROR! -> Only \$NUM_PIDS of $INGEST_CLI_NODE Ingest Clients are running!"
else
  echo "All Ingest Clients started within \$LONGEST seconds."
fi
EOT
# Copy file to local drives and launch them.
chmod 755 $INSTALL_DIR/iclient_verify
pdsh -w ^$INSTALL_DIR/acctservernodes 'cp $INSTALL_DIR/iclient_verify /$LOCAL_NVME1'
pdsh -w ^$INSTALL_DIR/acctservernodes '/$LOCAL_NVME1/iclient_verify'

# Clean up
rm $INSTALL_DIR/lnch_iclients 2>/dev/null
pdsh -w ^$INSTALL_DIR/acctservernodes 'rm /$LOCAL_NVME1/lnch_iclients 2>/dev/null' 2>/dev/null
rm $INSTALL_DIR/iclient_verify 2>/dev/null
pdsh -w ^$INSTALL_DIR/acctservernodes 'rm /$LOCAL_NVME1/iclient_verify 2>/dev/null' 2>/dev/null
