#!/bin/bash

# May 2021 - Gene Weber 
# This script is called by others and stops clients on the nodes running tservers.
# The calling script passes in the type of client to stop as $1.
# Used 3 loops instaed of 1 to improve accurace of test timing.
# All settings for this test are in acc_test.conf.

CLIENT_TYPE=$1

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars

# Loop through each tserver node and create the file to kill processes.
PIDDIR="/$LOCAL_NVME1/$A_PID_DIR"
PIDFILE="$PIDDIR/${CLIENT_TYPE}_clients.pid"
echo "Preparing to stop clients."
for node in $ACC_TSERVER_NODES
do
  # Using pkill to kill the children of the PIDs
  pdsh -w $node "cat $PIDFILE | sed 's/^.*$/pkill -P /' > $PIDDIR/temp1"
  pdsh -w $node "paste $PIDDIR/temp1 $PIDFILE >  $PIDDIR/temp2"
done

# Loop through each tserver node and kill $CLIENT_TYPE clients on each
echo $(date +%s) > client_stop
for node in $ACC_TSERVER_NODES
do
  echo "Stopping $CLIENT_TYPE clients on $node"
  pdsh -w $node "source $PIDDIR/temp2" 2>/dev/null # Don't background. Causes race with next line.
  pdsh -w $node "kill \$(cat $PIDFILE) 2>/dev/null" 2>/dev/null &
done

# Loop through each tserver node delete files
for node in $ACC_TSERVER_NODES
do
  pdsh -w $node "rm $PIDFILE $PIDDIR/temp1 $PIDDIR/temp2" &
done

