#!/bin/bash

# June 2021 - Gene Weber
# This script stops Hadoop and Zookeeper and cleans up.

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars
# Set bashrc flag
touch script_active

echo ""
echo "Stopping Proxy Server"
echo ""

# Stop Hadoop Proxy Server
pdsh -w ^$INSTALL_DIR/had_rsc_node "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop proxyserver"

echo ""
echo "Stopping Yarn Managers"
echo ""

# Stop Yarn node managers
pdsh -w ^$INSTALL_DIR/had_wkr_nodes "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop nodemanager"
# Stop Yarn resource manager
pdsh -w ^$INSTALL_DIR/had_rsc_node "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop resourcemanager"

echo ""
echo "Stopping HDFS"
echo ""

# Stop HDFS data nodes
pdsh -w ^$INSTALL_DIR/had_wkr_nodes "hdfs --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop datanode"
# Stop HDFS name node
pdsh -w ^$INSTALL_DIR/had_nam_node "hdfs --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop namenode"

echo ""
echo "Stopping Zookeeper"
echo ""

# Stop Zookeeper
pdsh -w ^$INSTALL_DIR/zoo_nodes "zkServer.sh stop $INSTALL_DIR/zookeeper-3.6.2/conf/zookeeper.cfg"

# Verify that all Hadoop processes have been stopped.
echo ""; echo "Verifying that all Hadoop processes are stopped."
cat <<EOT > $INSTALL_DIR/dead_yet
HAD_PROCS="datanode namenode nodemanager resourcemanager"
for proc in \$HAD_PROCS
do
  STILL_ALIVE=\$(ps -fu $LOGNAME | grep "\ -Dproc_\$proc\ " | wc -l)
  if (( \$STILL_ALIVE > 0 )); then
    echo "ERROR! -> \$STILL_ALIVE Hadoop \$proc process(s) still running."
  fi
done
STILL_ALIVE=\$(ps -fu $LOGNAME | grep "\ -Dzookeeper\." | wc -l)
if (( \$STILL_ALIVE > 0 )); then
  echo "ERROR! -> \$STILL_ALIVE Zookeeper process(s) still running."
fi
EOT
# Copy file to local drives and launch them.
chmod 755 $INSTALL_DIR/dead_yet
pdsh -w ^$INSTALL_DIR/all_nodes 'cp $INSTALL_DIR/dead_yet /$LOCAL_NVME1'
pdsh -w ^$INSTALL_DIR/all_nodes '/$LOCAL_NVME1/dead_yet'

# Clean up
rm $INSTALL_DIR/dead_yet 2>/dev/null
pdsh -w ^$INSTALL_DIR/all_nodes 'rm /$LOCAL_NVME1/dead_yet 2>/dev/null' 2>/dev/null

echo ""
echo "Before launching the acc_test_sw_install again, run the reset script."
echo ""

rm script_active
