#!/bin/bash

# March 2021 - Gene Weber
# This script stop Accumulo, and cleans up.

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=`cat inst_dir`
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars

echo ""
echo "Stopping the Accumulo Proxy"
echo ""

# Stop the accumulo Proxy
PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/acc_proxy.pid"
# Using pkill to kill the children of the PID
pdsh -w ^$INSTALL_DIR/acc_proxy_node "pkill -P \`cat $PIDFILE\`"
pdsh -w ^$INSTALL_DIR/acc_proxy_node "kill \`cat $PIDFILE\`" 2>/dev/null
pdsh -w ^$INSTALL_DIR/acc_proxy_node "rm $PIDFILE"

echo ""
echo "Stopping the Accumulo Tracer"
echo ""

# Stop the accumulo tracer
pdsh -w ^$INSTALL_DIR/acctracernodes 'accumulo-service tracer stop'

echo ""
echo "Stopping the Accumulo Garbage Collector"
echo ""

# Stop the accumulo garbage collector
pdsh -w ^$INSTALL_DIR/accgcnodes 'accumulo-service gc stop'

echo ""
echo "Stopping the Accumulo Masters"
echo ""

# Stop the accumulo master
pdsh -w ^$INSTALL_DIR/accmasternodes 'accumulo-service master stop'

echo ""
echo "Stopping the Accumulo Tablet Servers"
echo ""

# Stop the accumulo tablet servers
PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/tservers.pid"
for node in $ACC_TSERVER_NODES
do
  echo "Stopping tservers on $node"
  pdsh -w $node "kill \`cat $PIDFILE\`"
  pdsh -w $node "rm $PIDFILE"
done

echo ""
echo "Stopping the Accumulo Monitor"
echo ""

# Stop the accumulo monitor
pdsh -w ^$INSTALL_DIR/accmonitornodes 'accumulo-service monitor stop'

echo ""
echo "Deleting the  Accumulo database"
echo ""

hdfs dfs -rm -r /accumulo

echo ""
echo "If this looked successful, it's now safe to stop hadoop."
echo ""
