#!/bin/bash

# May 2021 - Gene Weber
# This script stops Hadoop and Zookeeper and cleans up.

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars

echo ""
echo "Stopping Proxy Server"
echo ""

# Stop Hadoop Proxy Server
pdsh -w ^$INSTALL_DIR/had_rsc_node "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop proxyserver"

echo ""
echo "Stopping Yarn Managers"
echo ""

# Stop Yarn node managers
pdsh -w ^$INSTALL_DIR/had_wkr_nodes "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop nodemanager"
# Stop Yarn resource manager
pdsh -w ^$INSTALL_DIR/had_rsc_node "yarn --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop resourcemanager"

echo ""
echo "Stopping HDFS"
echo ""

# Stop HDFS data nodes
pdsh -w ^$INSTALL_DIR/had_wkr_nodes "hdfs --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop datanode"
# Stop HDFS name node
pdsh -w ^$INSTALL_DIR/had_nam_node "hdfs --daemon stop --config $INSTALL_DIR/hadoop-3.1.2/etc/hadoop namenode"

echo ""
echo "Stopping Zookeeper"
echo ""

# Stop Zookeeper
pdsh -w ^$INSTALL_DIR/zoo_nodes "zkServer.sh stop $INSTALL_DIR/zookeeper-3.6.2/conf/zookeeper.cfg"

echo ""
echo "Before launching the acc_test_sw_install again, run the reset script."
echo ""

