#!/bin/bash

# Gene Weber - March 2021
# This script stops the batchwalk clients on the nodes running tservers.
# All settings for this test are in acc_test.conf.

# Call generic stop clients script specifying batchwalk.
./stop_clients batchwalk
rm client_stop 2>/dev/null
