#!/bin/bash

# May 2021 - Gene Weber 
# This script stops the walk clients on the nodes running tservers.
# All settings for this test are in acc_test.conf.

# Call generic stop clients script specifying walk.
./stop_clients walk
rm client_stop 2>/dev/null
