#!/bin/bash

# June 2021 - Gene Weber
# This script stops Accumulo, and cleans up.
#

# Location of existing directory on shared file system of installed software.
INSTALL_DIR=$(cat inst_dir)
# Execute the configuration file to initialize all needed variables.
source acc_test.conf
# Get all needed environmental variables.
source $INSTALL_DIR/acc_env_vars
# Set bashrc flag
touch script_active

if [ -f $INSTALL_DIR/acc_proxy_running ]; then
  echo ""
  echo "Stopping the Accumulo Proxy"
  echo ""
  
  # Stop the accumulo Proxy
  PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/acc_proxy.pid"
  # Using pkill to kill the children of the PID
  pdsh -w ^$INSTALL_DIR/acc_proxy_node "pkill -P \$(cat $PIDFILE)"
  pdsh -w ^$INSTALL_DIR/acc_proxy_node "kill \$(cat $PIDFILE)" 2>/dev/null
  pdsh -w ^$INSTALL_DIR/acc_proxy_node "rm $PIDFILE"
  rm $INSTALL_DIR/acc_proxy_running
fi

echo ""
echo "Stopping the Accumulo Tracer"
echo ""

# Stop the accumulo tracer
pdsh -w ^$INSTALL_DIR/acctracernodes 'accumulo-service tracer stop'

echo ""
echo "Stopping the Accumulo Garbage Collector"
echo ""

# Stop the accumulo garbage collector
pdsh -w ^$INSTALL_DIR/accgcnodes 'accumulo-service gc stop'

echo ""
echo "Stopping the Accumulo Masters"
echo ""

# Stop the accumulo master
pdsh -w ^$INSTALL_DIR/accmasternodes 'accumulo-service master stop'

echo ""
echo "Stopping the Accumulo Tablet Servers on each of these nodes:"
echo "$ACC_TSERVER_NODES"

# Stop the accumulo tablet servers
PIDFILE="/$LOCAL_NVME1/$A_PID_DIR/tservers.pid"
pdsh -w ^$INSTALL_DIR/acctservernodes "kill \$(cat $PIDFILE) 2>/dev/null" 2>/dev/null &
pdsh -w ^$INSTALL_DIR/acctservernodes "rm $PIDFILE 2>/dev/null" 2>/dev/null &

echo ""
echo "Stopping the Accumulo Monitor"
echo ""

# Stop the accumulo monitor
pdsh -w ^$INSTALL_DIR/accmonitornodes 'accumulo-service monitor stop'

# Clean up Accumulo database.
echo ""
echo "Clearing old data from Zookeeper."
echo ""

# Run ZooZap to remove old artifacts from Zookeeper.
pdsh -w ^$INSTALL_DIR/zoo_nodes 'accumulo org.apache.accumulo.server.util.ZooZap -verbose -master -tservers -tracers'

echo ""
echo "Deleting the  Accumulo database"
echo ""

hdfs dfs -rm -skipTrash -r /accumulo
hdfs dfsadmin -report >/dev/null # This seems to force reclaimation of HDFS disk space.

# Verify that all Accumulo processes have been stopped.
echo ""; echo "Verifying that all Accumulo processes are stopped."
cat <<EOT > $INSTALL_DIR/dead_yet
ACC_PROCS="tserver master monitor gc tracer"
for proc in \$ACC_PROCS
do
  STILL_ALIVE=\$(ps -fu $LOGNAME | grep "\ \$proc\$" | wc -l)
  if (( \$STILL_ALIVE > 0 )); then
    echo "ERROR! -> \$STILL_ALIVE Accumulo \$proc process(s) still running."
  fi
done
EOT
# Copy file to local drives and launch them.
chmod 755 $INSTALL_DIR/dead_yet
pdsh -w ^$INSTALL_DIR/all_nodes 'cp $INSTALL_DIR/dead_yet /$LOCAL_NVME1'
pdsh -w ^$INSTALL_DIR/all_nodes '/$LOCAL_NVME1/dead_yet'

# Clean up
rm $INSTALL_DIR/dead_yet 2>/dev/null
pdsh -w ^$INSTALL_DIR/all_nodes 'rm /$LOCAL_NVME1/dead_yet 2>/dev/null' 2>/dev/null

echo ""
echo "If this looked successful, it's now safe to stop hadoop."
echo ""

rm script_active
